version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: studychum-sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
